# Generated by Django 4.0.2 on 2022-06-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dijk', '0007_amenity_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Équipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('adresse', models.TextField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('lien_officiel', models.URLField(blank=True, default=None, null=True)),
                ('texte_autres_liens', models.TextField(blank=True, default=None, null=True)),
                ('typeLieu', models.ManyToManyField(to='mapmomes.TypeLieu')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
                ('équipement', models.ManyToManyField(to='mapmomes.Équipement')),
            ],
        ),
    ]
